config/routes.rb
Rails.application.routes.draw do
  resources :auctions

  root to: "auctions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auction.rb
class Auction < ApplicationRecord
  has_many :sales, dependent: :destroy
  validates_uniqueness_of :name
  validates_presence_of :name

  def upload(file)
    CSV.foreach(file.path, headers: true) do |row|
      if row.present?
        @auction = Auction.find_or_create_by(name: row["auction name"])

        # if the address happens to be blank, fill it out from the row
        @auction.street_address ||= row["street address"]
        @auction.city           ||= row["city"]
        @auction.state          ||= row["state"]
        @auction.save!

        @sale = Sale.create!(
          auction_id: @auction.id,
          vehicle_year: row["vehicle year"],
          vehicle_make: row["vehicle make"],
          vehicle_model: row["vehicle model"],
          vehicle_stock_number: row["vehicle stock number"],
          winning_bid: row["winning bid"],
          seller_payout: row["seller payout"],
          description: row["description"],
        )
      end
    end
  end

  def total_profit
    profit = 0
    self.sales.each do |sale|
      profit += sale.winning_bid - sale.seller_payout
    end
    profit
  end

  def average_profit
    profit = 0
    self.sales.each do |sale|
      profit += sale.winning_bid - sale.seller_payout
    end
    profit / self.sales.count
  end
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :auction

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_action :set_auction, only: [:show, :edit, :update, :destroy]

  # GET /auctions
  # GET /auctions.json
  def index
    @auctions = Auction.all
  end

  # GET /auctions/1
  # GET /auctions/1.json
  def show
  end

  # GET /auctions/new
  def new
    @auction = Auction.new
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new().upload(params[:file])
    redirect_to auctions_path
  end

  # PATCH/PUT /auctions/1
  # PATCH/PUT /auctions/1.json
  def update
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction.destroy
    respond_to do |format|
      format.html { redirect_to auctions_url, notice: 'Auction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auction
      @auction = Auction.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_form.html.erb
<%= form_tag '/auctions', multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload" %>
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing Auction</h1>

<%= render 'form', auction: @auction %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Auctions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr class='strong'>
      <td>Auction Name</td>
      <td>Auction City</td>
      <td>Number of Sales</td>
      <td>Total Profit</td>
      <td>Average Profit</td>
    </tr>
    <% @auctions.each do |auction| %>
      <tr>
        <td><%= auction.name %></td>
        <td><%= auction.city %></td>
        <td><%= auction.sales.count %></td>
        <td><%= number_to_currency(auction.total_profit) %></td>
        <td><%= number_to_currency(auction.average_profit) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Auction', new_auction_path %>

app/views/auctions/new.html.erb
<h1>New Auction</h1>

<%= render 'form', auction: @auction %>

app/views/auctions/show.html.erb
<p id="notice"><%= notice %></p>

<p><%= @auction.name %></p>

<%= link_to 'Back', auctions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionDigester</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>